/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MISO_2_aliases.h"
#include "MISO_2.h"
#include "MOSI_2_aliases.h"
#include "MOSI_2.h"
#include "SCLK_2_aliases.h"
#include "SCLK_2.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "SS_aliases.h"
#include "SS.h"
#include "PGA_SpeedControl.h"
#include "Speed_pin_aliases.h"
#include "Speed_pin.h"
#include "UART_1.h"
#include "isr_uart_rx.h"
#include "VDAC8_SpeedControl.h"
#include "Enable_pin_aliases.h"
#include "Enable_pin.h"
#include "LED_pin_aliases.h"
#include "LED_pin.h"
#include "Clock_TempSampling.h"
#include "RTD_1.h"
#include "Temp_sample_counter.h"
#include "isr_clock.h"
#include "Switch_output_aliases.h"
#include "Switch_output.h"
#include "Switch_input_aliases.h"
#include "Switch_input.h"
#include "switch_input_interrupt.h"
#include "VDAC8_Enabling.h"
#include "VDAC8_Direction.h"
#include "Direction_pin_aliases.h"
#include "Direction_pin.h"
#include "SPIM_1_IntClock.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

